// <auto-generated />
using System;
using HuellitasSV.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellitasSV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924024556_AgregarTablaCuenta")]
    partial class AgregarTablaCuenta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellitasSV.API.Models.Cuenta", b =>
                {
                    b.Property<long>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCuenta"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("IdCuenta");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("cuenta");

                    b.HasData(
                        new
                        {
                            IdCuenta = 1001L,
                            Contrasena = "Refugio2026!",
                            Correo = "contacto@huellitassv.org",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1002L,
                            Contrasena = "Refugio2026!",
                            Correo = "adopciones@proteccionsv.org",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1003L,
                            Contrasena = "Refugio2026!",
                            Correo = "info@alberguesm.org",
                            Estado = "pendiente",
                            Rol = "Refugio"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.Property<long>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMascota"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("int")
                        .HasColumnName("edad_meses");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imagen_content_type");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen_data");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tamano");

                    b.HasKey("IdMascota");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRefugio");

                    b.ToTable("mascota");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Refugio", b =>
                {
                    b.Property<long>("IdRefugio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRefugio"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("DocumentacionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("documentacion_url");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_aprobacion");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_organizacion");

                    b.HasKey("IdRefugio");

                    b.HasIndex("EstadoAprobacion");

                    b.ToTable("refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");
                });
#pragma warning restore 612, 618
        }
    }
}
