// <auto-generated />
using System;
using HuellitasSV.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellitasSV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924042215_MejorasSeguridad")]
    partial class MejorasSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellitasSV.API.Models.Cuenta", b =>
                {
                    b.Property<long>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCuenta"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("bit")
                        .HasColumnName("correo_verificado");

                    b.Property<bool>("DosFactores")
                        .HasColumnType("bit")
                        .HasColumnName("dos_factores");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("IdCuenta");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("cuenta");

                    b.HasData(
                        new
                        {
                            IdCuenta = 1001L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "contacto@huellitassv.org",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1002L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "adopciones@proteccionsv.org",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1003L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "info@alberguesm.org",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9001L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "losamigos.refugio@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9002L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "hogarsantaana@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9003L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "vidasonsonate@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9004L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "patitasusulutan@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9005L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "ayudaanimalchalate@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "rechazado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9006L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "marialopez@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "activo",
                            Rol = "Usuario"
                        },
                        new
                        {
                            IdCuenta = 9007L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "carlosperez@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "inactivo",
                            Rol = "Usuario"
                        },
                        new
                        {
                            IdCuenta = 9008L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "anagomez@correo.com",
                            CorreoVerificado = true,
                            DosFactores = false,
                            Estado = "bloqueado",
                            Rol = "Usuario"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.Property<long>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMascota"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("int")
                        .HasColumnName("edad_meses");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imagen_content_type");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen_data");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tamano");

                    b.HasKey("IdMascota");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRefugio");

                    b.ToTable("mascota");

                    b.HasData(
                        new
                        {
                            IdMascota = 9001L,
                            EdadMeses = 48,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Rocky II",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9002L,
                            EdadMeses = 8,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Mia",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9003L,
                            EdadMeses = 30,
                            Especie = "perro",
                            Estado = "reservada",
                            EstadoSalud = "en_tratamiento",
                            FechaRegistro = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Bobby",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9004L,
                            EdadMeses = 18,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "crónico",
                            FechaRegistro = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Coco",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9005L,
                            EdadMeses = 60,
                            Especie = "perro",
                            Estado = "adoptada",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Thor",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9006L,
                            EdadMeses = 4,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9001L,
                            ImagenUrl = "https://placekitten.com/400/300",
                            Nombre = "Nina",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9007L,
                            EdadMeses = 10,
                            Especie = "otro",
                            Estado = "disponible",
                            EstadoSalud = "discapacidad",
                            FechaRegistro = new DateTime(2026, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9001L,
                            Nombre = "Simón",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9008L,
                            EdadMeses = 24,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            ImagenUrl = "https://placedog.net/500/400",
                            Nombre = "Duke",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9009L,
                            EdadMeses = 14,
                            Especie = "gato",
                            Estado = "en_tratamiento",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 8, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            Nombre = "Pelusa",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9010L,
                            EdadMeses = 36,
                            Especie = "perro",
                            Estado = "fallecida",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            Nombre = "Zeus",
                            Tamano = "mediano"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Refugio", b =>
                {
                    b.Property<long>("IdRefugio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRefugio"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("DocumentacionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("documentacion_url");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_aprobacion");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_organizacion");

                    b.HasKey("IdRefugio");

                    b.HasIndex("EstadoAprobacion");

                    b.ToTable("refugio");

                    b.HasData(
                        new
                        {
                            IdRefugio = 9001L,
                            Contacto = "7770-0001",
                            Departamento = "San Salvador",
                            DocumentacionUrl = "https://losamigos.org/docs",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 9001L,
                            Municipio = "San Salvador",
                            NombreOrganizacion = "Refugio Los Amigos"
                        },
                        new
                        {
                            IdRefugio = 9002L,
                            Contacto = "7770-0002",
                            Departamento = "Santa Ana",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 9002L,
                            Municipio = "Santa Ana",
                            NombreOrganizacion = "Hogar Animal Santa Ana"
                        },
                        new
                        {
                            IdRefugio = 9003L,
                            Contacto = "7770-0003",
                            Departamento = "Sonsonate",
                            EstadoAprobacion = "pendiente",
                            IdCuenta = 9003L,
                            Municipio = "Sonsonate",
                            NombreOrganizacion = "Vida Animal Sonsonate"
                        },
                        new
                        {
                            IdRefugio = 9004L,
                            Contacto = "7770-0004",
                            Departamento = "Usulután",
                            DocumentacionUrl = "https://patitasusulutan.org/docs",
                            EstadoAprobacion = "pendiente",
                            IdCuenta = 9004L,
                            Municipio = "Usulután",
                            NombreOrganizacion = "Patitas de Usulután"
                        },
                        new
                        {
                            IdRefugio = 9005L,
                            Contacto = "7770-0005",
                            Departamento = "Chalatenango",
                            EstadoAprobacion = "rechazado",
                            IdCuenta = 9005L,
                            Municipio = "Chalatenango",
                            NombreOrganizacion = "Ayuda Animal Chalatenango"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.TokenSeguridad", b =>
                {
                    b.Property<long>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_token");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdToken"));

                    b.Property<DateTime>("Expira")
                        .HasColumnType("datetime2")
                        .HasColumnName("expira");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("valor");

                    b.HasKey("IdToken");

                    b.HasIndex("IdCuenta");

                    b.ToTable("token_seguridad");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCuenta");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            IdUsuario = 9001L,
                            IdCuenta = 9006L,
                            Nombre = "María López"
                        },
                        new
                        {
                            IdUsuario = 9002L,
                            IdCuenta = 9007L,
                            Nombre = "Carlos Pérez"
                        },
                        new
                        {
                            IdUsuario = 9003L,
                            IdCuenta = 9008L,
                            Nombre = "Ana Gómez"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");
                });
#pragma warning restore 612, 618
        }
    }
}
