// <auto-generated />
using System;
using HuellitasSV.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellitasSV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921050406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.Property<long>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMascota"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("int")
                        .HasColumnName("edad_meses");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imagen_content_type");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen_data");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tamano");

                    b.HasKey("IdMascota");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRefugio");

                    b.ToTable("mascota", (string)null);
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Refugio", b =>
                {
                    b.Property<long>("IdRefugio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRefugio"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contacto");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("DocumentacionUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("documentacion_url");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_aprobacion");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_organizacion");

                    b.HasKey("IdRefugio");

                    b.ToTable("refugio", (string)null);
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");
                });
#pragma warning restore 612, 618
        }
    }
}
