// <auto-generated />
using System;
using HuellitasSV.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellitasSV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922173816_AgregaSolicitudesReportesNotificaciones")]
    partial class AgregaSolicitudesReportesNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.Property<long>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMascota"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("int")
                        .HasColumnName("edad_meses");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imagen_content_type");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen_data");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tamano");

                    b.HasKey("IdMascota");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRefugio");

                    b.ToTable("mascota");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.NecesidadDonacion", b =>
                {
                    b.Property<int>("IdNecesidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNecesidad"));

                    b.Property<decimal>("CantidadCubierta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadRequerida")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNecesidad");

                    b.HasIndex("IdRefugio");

                    b.ToTable("NecesidadesDonacion");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdRefugio")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdRefugio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Refugio", b =>
                {
                    b.Property<long>("IdRefugio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRefugio"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("DocumentacionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("documentacion_url");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_aprobacion");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float")
                        .HasColumnName("longitud");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_organizacion");

                    b.HasKey("IdRefugio");

                    b.HasIndex("EstadoAprobacion");

                    b.ToTable("refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.ReporteAnimal", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("IdRefugio")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdRefugio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReportesAnimales");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.SolicitudAdopcion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("ComentarioDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdMascota")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SolicitudesAdopcion");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.NecesidadDonacion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Notificacion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Refugio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.ReporteAnimal", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.SolicitudAdopcion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
