// <auto-generated />
using System;
using HuellitasSV.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellitasSV.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925071400_AgregaCuentaAdminYSeguridad")]
    partial class AgregaCuentaAdminYSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellitasSV.API.Models.Anuncio", b =>
                {
                    b.Property<long>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_anuncio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAnuncio"));

                    b.Property<string>("ContactoTienda")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto_tienda");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("NombreTienda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_tienda");

                    b.Property<bool>("PagoConfirmado")
                        .HasColumnType("bit")
                        .HasColumnName("pago_confirmado");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdAnuncio");

                    b.ToTable("anuncio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Cuenta", b =>
                {
                    b.Property<long>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCuenta"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("IdCuenta");

                    b.ToTable("cuenta");

                    b.HasData(
                        new
                        {
                            IdCuenta = 1L,
                            Contrasena = "AQAAAAIAAYagAAAAECJkUTNTpDEXyGK0S6lDi/pF5uh9pDEYK2H/U3+h/ciWOS/vclz8lBWHa+9Vy2kCAg==",
                            Correo = "admin@huellitassv.org",
                            Estado = "aprobado",
                            Rol = "Admin"
                        },
                        new
                        {
                            IdCuenta = 1001L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "contacto@huellitassv.org",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1002L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "adopciones@proteccionsv.org",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 1003L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "info@alberguesm.org",
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9001L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "losamigos.refugio@correo.com",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9002L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "hogarsantaana@correo.com",
                            Estado = "aprobado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9003L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "vidasonsonate@correo.com",
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9004L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "patitasusulutan@correo.com",
                            Estado = "pendiente",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9005L,
                            Contrasena = "AQAAAAIAAYagAAAAEGpRavkRHJ/aY735e72svpCHsB4bya3yjaaoTgFIkSImDf/aT31gaWTTjv2yG1cSQg==",
                            Correo = "ayudaanimalchalate@correo.com",
                            Estado = "rechazado",
                            Rol = "Refugio"
                        },
                        new
                        {
                            IdCuenta = 9006L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "marialopez@correo.com",
                            Estado = "activo",
                            Rol = "Usuario"
                        },
                        new
                        {
                            IdCuenta = 9007L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "carlosperez@correo.com",
                            Estado = "inactivo",
                            Rol = "Usuario"
                        },
                        new
                        {
                            IdCuenta = 9008L,
                            Contrasena = "AQAAAAIAAYagAAAAEEwuG7WIzT50BNMbcOjCcrOXbVZYK+aPbwJW8gVrFg1VQ5QqPmopibuNtnP7+aCn5A==",
                            Correo = "anagomez@correo.com",
                            Estado = "bloqueado",
                            Rol = "Usuario"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.Property<long>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMascota"));

                    b.Property<int>("EdadMeses")
                        .HasColumnType("int")
                        .HasColumnName("edad_meses");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoSalud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_salud");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imagen_content_type");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen_data");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tamano");

                    b.HasKey("IdMascota");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRefugio");

                    b.ToTable("mascota");

                    b.HasData(
                        new
                        {
                            IdMascota = 1L,
                            EdadMeses = 24,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Firulais",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 2L,
                            EdadMeses = 12,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Michi",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 3L,
                            EdadMeses = 36,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "en_tratamiento",
                            FechaRegistro = new DateTime(2026, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Rex",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 4L,
                            EdadMeses = 18,
                            Especie = "perro",
                            Estado = "adoptada",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Luna",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 5L,
                            EdadMeses = 6,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Simba",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 6L,
                            EdadMeses = 48,
                            Especie = "perro",
                            Estado = "en_tratamiento",
                            EstadoSalud = "crónico",
                            FechaRegistro = new DateTime(2026, 2, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 3L,
                            Nombre = "Rocky",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9001L,
                            EdadMeses = 48,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Rocky II",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9002L,
                            EdadMeses = 8,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Mia",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9003L,
                            EdadMeses = 30,
                            Especie = "perro",
                            Estado = "reservada",
                            EstadoSalud = "en_tratamiento",
                            FechaRegistro = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 1L,
                            Nombre = "Bobby",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9004L,
                            EdadMeses = 18,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "crónico",
                            FechaRegistro = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Coco",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9005L,
                            EdadMeses = 60,
                            Especie = "perro",
                            Estado = "adoptada",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 7, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 2L,
                            Nombre = "Thor",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9006L,
                            EdadMeses = 4,
                            Especie = "gato",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 7, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9001L,
                            ImagenUrl = "https://placekitten.com/400/300",
                            Nombre = "Nina",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9007L,
                            EdadMeses = 10,
                            Especie = "otro",
                            Estado = "disponible",
                            EstadoSalud = "discapacidad",
                            FechaRegistro = new DateTime(2026, 8, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9001L,
                            Nombre = "Simón",
                            Tamano = "pequeño"
                        },
                        new
                        {
                            IdMascota = 9008L,
                            EdadMeses = 24,
                            Especie = "perro",
                            Estado = "disponible",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            ImagenUrl = "https://placedog.net/500/400",
                            Nombre = "Duke",
                            Tamano = "grande"
                        },
                        new
                        {
                            IdMascota = 9009L,
                            EdadMeses = 14,
                            Especie = "gato",
                            Estado = "en_tratamiento",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 8, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            Nombre = "Pelusa",
                            Tamano = "mediano"
                        },
                        new
                        {
                            IdMascota = 9010L,
                            EdadMeses = 36,
                            Especie = "perro",
                            Estado = "fallecida",
                            EstadoSalud = "sano",
                            FechaRegistro = new DateTime(2026, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            IdRefugio = 9002L,
                            Nombre = "Zeus",
                            Tamano = "mediano"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.NecesidadDonacion", b =>
                {
                    b.Property<long>("IdNecesidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_necesidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNecesidad"));

                    b.Property<decimal>("CantidadCubierta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cantidad_cubierta");

                    b.Property<decimal>("CantidadRequerida")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cantidad_requerida");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_publicacion");

                    b.Property<long>("IdRefugio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    b.Property<string>("TipoInsumo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_insumo");

                    b.HasKey("IdNecesidad");

                    b.HasIndex("IdRefugio");

                    b.ToTable("necesidad_donacion");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdRefugio")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdRefugio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Refugio", b =>
                {
                    b.Property<long>("IdRefugio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_refugio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRefugio"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("DocumentacionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("documentacion_url");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_aprobacion");

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float")
                        .HasColumnName("longitud");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_organizacion");

                    b.HasKey("IdRefugio");

                    b.HasIndex("EstadoAprobacion");

                    b.ToTable("refugio");

                    b.HasData(
                        new
                        {
                            IdRefugio = 1L,
                            Contacto = "contacto@huellitassv.org",
                            Departamento = "San Salvador",
                            DocumentacionUrl = "https://huellitassv.org/docs",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 1001L,
                            Municipio = "San Salvador",
                            NombreOrganizacion = "Refugio Huellitas San Salvador"
                        },
                        new
                        {
                            IdRefugio = 2L,
                            Contacto = "adopciones@proteccionsv.org",
                            Departamento = "La Libertad",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 1002L,
                            Municipio = "Santa Tecla",
                            NombreOrganizacion = "Protección Animal Santa Tecla"
                        },
                        new
                        {
                            IdRefugio = 3L,
                            Contacto = "info@alberguesm.org",
                            Departamento = "San Miguel",
                            DocumentacionUrl = "https://alberguesm.org/documentos",
                            EstadoAprobacion = "pendiente",
                            IdCuenta = 1003L,
                            Municipio = "San Miguel",
                            NombreOrganizacion = "Albergue Canino San Miguel"
                        },
                        new
                        {
                            IdRefugio = 9001L,
                            Contacto = "7770-0001",
                            Departamento = "San Salvador",
                            DocumentacionUrl = "https://losamigos.org/docs",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 9001L,
                            Municipio = "San Salvador",
                            NombreOrganizacion = "Refugio Los Amigos"
                        },
                        new
                        {
                            IdRefugio = 9002L,
                            Contacto = "7770-0002",
                            Departamento = "Santa Ana",
                            EstadoAprobacion = "aprobado",
                            IdCuenta = 9002L,
                            Municipio = "Santa Ana",
                            NombreOrganizacion = "Hogar Animal Santa Ana"
                        },
                        new
                        {
                            IdRefugio = 9003L,
                            Contacto = "7770-0003",
                            Departamento = "Sonsonate",
                            EstadoAprobacion = "pendiente",
                            IdCuenta = 9003L,
                            Municipio = "Sonsonate",
                            NombreOrganizacion = "Vida Animal Sonsonate"
                        },
                        new
                        {
                            IdRefugio = 9004L,
                            Contacto = "7770-0004",
                            Departamento = "Usulután",
                            DocumentacionUrl = "https://patitasusulutan.org/docs",
                            EstadoAprobacion = "pendiente",
                            IdCuenta = 9004L,
                            Municipio = "Usulután",
                            NombreOrganizacion = "Patitas de Usulután"
                        },
                        new
                        {
                            IdRefugio = 9005L,
                            Contacto = "7770-0005",
                            Departamento = "Chalatenango",
                            EstadoAprobacion = "rechazado",
                            IdCuenta = 9005L,
                            Municipio = "Chalatenango",
                            NombreOrganizacion = "Ayuda Animal Chalatenango"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.ReporteAnimal", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("IdRefugio")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdRefugio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ReportesAnimales");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.SolicitudAdopcion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("ComentarioDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdMascota")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("SolicitudesAdopcion");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<long>("IdCuenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cuenta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCuenta");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            IdUsuario = 9001L,
                            IdCuenta = 9006L,
                            Nombre = "María López"
                        },
                        new
                        {
                            IdUsuario = 9002L,
                            IdCuenta = 9007L,
                            Nombre = "Carlos Pérez"
                        },
                        new
                        {
                            IdUsuario = 9003L,
                            IdCuenta = 9008L,
                            Nombre = "Ana Gómez"
                        });
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Mascota", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.NecesidadDonacion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refugio");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.Notificacion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Refugio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.ReporteAnimal", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Refugio", "Refugio")
                        .WithMany()
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Refugio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HuellitasSV.API.Models.SolicitudAdopcion", b =>
                {
                    b.HasOne("HuellitasSV.API.Models.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuellitasSV.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
